<div class="cart-tiles__section">   
    <h2 class="cart-tiles__title">Recently Viewed Products</h2>
</div>

<div class="cart-tiles__tiles-container">
    <div class="cart-tiles__img-container">
        <img width="333" height="333" class="cart-tiles__img"  src="<?php echo $block->getViewFileUrl("images/cart-tiles/web/11 1.png")?>" alt="11 1">
        <div class="cart-tiles__img-bottom-container">
            <h3 class="cart-tiles__img-bottom-title">Windsor White Oak</h3>
            <div class="cart-tiles__img-bottom-content">
                <span class="cart-tiles__canceled-sar">449.99 SAR</span>
                <span class="cart-tiles__sar">312.49 SAR</span>
            </div>
        </div>
    </div>
    <div class="cart-tiles__img-container">
        <img width="333" height="333" class="cart-tiles__img"  src="<?php echo $block->getViewFileUrl("images/cart-tiles/web/10 1.png")?>" alt="10 1">
        <div class="cart-tiles__img-bottom-container">
            <h3 class="cart-tiles__img-bottom-title">Sicily Grey Décor 30×60</h3>
            <div class="cart-tiles__img-bottom-content">
                <span class="cart-tiles__canceled-sar">449.99 SAR</span>
                <span class="cart-tiles__sar">312.49 SAR</span>
            </div>
        </div>
    </div>
    <div class="cart-tiles__img-container">
        <img width="333" height="333" class="cart-tiles__img"  src="<?php echo $block->getViewFileUrl("images/cart-tiles/web/9 61.png")?>" alt="9 61">
        <div class="cart-tiles__img-bottom-container">
            <h3 class="cart-tiles__img-bottom-title">Sardinia White</h3>
            <div class="cart-tiles__img-bottom-content">
                <span class="cart-tiles__canceled-sar">449.99 SAR</span>
                <span class="cart-tiles__sar">312.49 SAR</span>
            </div>
        </div>
    </div>
    <div class="cart-tiles__img-container">
        <img width="333" height="333" class="cart-tiles__img"  src="<?php echo $block->getViewFileUrl("images/cart-tiles/web/8 1.png")?>" alt="8 1">
        <div class="cart-tiles__img-bottom-container">
            <h3 class="cart-tiles__img-bottom-title">Sicily Grey 30×60</h3>
            <div class="cart-tiles__img-bottom-content">
                <span class="cart-tiles__canceled-sar">449.99 SAR</span>
                <span class="cart-tiles__sar">312.49 SAR</span>
            </div>
        </div>
    </div>
</div>