<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
            <script type="text/x-magento-init">	
{	
   "*": {	
	   "Magento_Ui/js/core/app": {
	       "components": {
	           "change_qty": {
	               "component": "Magento_Catalog/js/change_qty",
	               "defaultQty": <?php echo $block->getProductDefaultQty() * 1 ?>
	           }
	       }
	   }
   }	
}	
</script>
        <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <div class="control" data-bind="scope: 'change_qty'">
                <button data-bind="click: decreaseQty" class="qty-action qty-action--decrement">&ndash;</button>
                <input type="number"
                       name="qty"
                       id="qty"
                       min="0"
                       data-bind="value: qty()"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
                <button data-bind="click: increaseQty" class="qty-action qty-action--increment">+</button>
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
