<div class="hero__img-container">
    <img width="1920" height="526" class="hero__img hero__img--web"  src="<?php echo $block->getViewFileUrl("images/hero.png")?>" alt="hero">
    <img width="1232" height="434" class="hero__img hero__img--mobile" src="<?php echo $block->getViewFileUrl("images/hero-mobile.png")?>" alt="hero">
</div>
<section class="hero__section">   
    <h2 class="hero__title">New Generation Ceramic Tile</h2>
    <p class="hero__content">Penatibus sem vitae mollis luctus mi tellus. Maximus eu eleifend aptent dapibus metus maecenas consequat. Elementum interdum a semper. Netus nullam eros nisi volutpat nibh ex ultricies. Pharetra sagittis sit aliquet at. Magna nam platea justo.
    </p>
    <button type="button" class="hero__btn hero__btn--secondary">
        Learn More
    </button>
</section>