<section class="home-showroom__section">   
    <h2 class="home-showroom__title">Our Showrooms</h2>
    <p class="home-showroom__content">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text.
    </p>
    <button type="button" class="home-showroom__btn home-showroom__btn--primary">
        Learn More
    </button>
</section>

<div class="home-showroom__img-container">
    <img width="817" height="649" class="home-showroom__img home-showroom__img--web"  src="<?php echo $block->getViewFileUrl("images/showroom-web.png")?>" alt="home-showroom">
    <img width="943" height="669" class="home-showroom__img home-showroom__img--mobile" src="<?php echo $block->getViewFileUrl("images/showroom-mobile.png")?>" alt="home-showroom">
</div>
