<section class="home-vision__section">   
    <h2 class="home-vision__title">Vision</h2>
    <p class="home-vision__content">Penatibus sem vitae mollis luctus mi tellus. Maximus eu eleifend aptent dapibus metus maecenas consequat. Elementum interdum a semper. Netus nullam eros nisi volutpat nibh ex ultricies. Pharetra sagittis sit aliquet at. Magna nam platea justo.
    </p>
    <button type="button" class="home-vision__btn home-vision__btn--primary">
        Learn More
    </button>
</section>

<div class="home-vision__img-container">
    <img width="1324" height="883" class="home-vision__img home-vision__img--web"  src="<?php echo $block->getViewFileUrl("images/vision.png")?>" alt="vision">
    <img width="435" height="971" class="home-vision__img home-vision__img--mobile" src="<?php echo $block->getViewFileUrl("images/vision-mobile.png")?>" alt="vision">
</div>
