<div class="catalog-tiles__tiles-container">
    <div class="catalog-tiles__img-container">
        <img width="333" height="333" class="catalog-tiles__img"  src="<?php echo $block->getViewFileUrl("images/catalog-tiles/web/15 1.png")?>" alt="15 1">
        <div class="catalog-tiles__img-bottom-container">
            <h3 class="catalog-tiles__img-bottom-title">Zurich Vision 60×60</h3>
            <div class="catalog-tiles__img-bottom-content">
                <span class="catalog-tiles__canceled-sar">449.99 SAR</span>
                <span class="catalog-tiles__sar">237.99 SAR</span>
            </div>
        </div>
    </div>
    <div class="catalog-tiles__img-container">
        <img width="333" height="333" class="catalog-tiles__img"  src="<?php echo $block->getViewFileUrl("images/catalog-tiles/web/14 1.png")?>" alt="14 1">
        <div class="catalog-tiles__img-bottom-container">
            <h3 class="catalog-tiles__img-bottom-title">Zurich Pearl 60×60</h3>
            <div class="catalog-tiles__img-bottom-content">
                <span class="catalog-tiles__canceled-sar">449.99 SAR</span>
                <span class="catalog-tiles__sar">312.49 SAR</span>
            </div>
        </div>
    </div>
    <div class="catalog-tiles__img-container">
        <img width="333" height="333" class="catalog-tiles__img"  src="<?php echo $block->getViewFileUrl("images/catalog-tiles/web/13 1.png")?>" alt="13 1">
        <div class="catalog-tiles__img-bottom-container">
            <h3 class="catalog-tiles__img-bottom-title">Zurich Grey 60×60</h3>
            <div class="catalog-tiles__img-bottom-content">
                <span class="catalog-tiles__canceled-sar">449.99 SAR</span>
                <span class="catalog-tiles__sar">312.49 SAR</span>
            </div>
        </div>
    </div>
    <div class="catalog-tiles__img-container">
        <img width="333" height="333" class="catalog-tiles__img"  src="<?php echo $block->getViewFileUrl("images/catalog-tiles/web/12 1.png")?>" alt="12 1">
        <div class="catalog-tiles__img-bottom-container">
            <h3 class="catalog-tiles__img-bottom-title">Zurich Dark Grey 60×60</h3>
            <div class="catalog-tiles__img-bottom-content">
                <span class="catalog-tiles__canceled-sar">449.99 SAR</span>
                <span class="catalog-tiles__sar">312.49 SAR</span>
            </div>
        </div>
    </div>
    <div class="catalog-tiles__img-container">
        <img width="333" height="333" class="catalog-tiles__img"  src="<?php echo $block->getViewFileUrl("images/catalog-tiles/web/11 1.png")?>" alt="11 1">
        <div class="catalog-tiles__img-bottom-container">
            <h3 class="catalog-tiles__img-bottom-title">Windsor White Oak</h3>
            <div class="catalog-tiles__img-bottom-content">
                <span class="catalog-tiles__canceled-sar">449.99 SAR</span>
                <span class="catalog-tiles__sar">312.49 SAR</span>
            </div>
        </div>
    </div>
    <div class="catalog-tiles__img-container">
        <img width="333" height="333" class="catalog-tiles__img"  src="<?php echo $block->getViewFileUrl("images/catalog-tiles/web/10 1.png")?>" alt="10 1">
        <div class="catalog-tiles__img-bottom-container">
            <h3 class="catalog-tiles__img-bottom-title">Sicily Grey Décor 30×60</h3>
            <div class="catalog-tiles__img-bottom-content">
                <span class="catalog-tiles__canceled-sar">449.99 SAR</span>
                <span class="catalog-tiles__sar">312.49 SAR</span>
            </div>
        </div>
    </div>
    <div class="catalog-tiles__img-container">
        <img width="333" height="333" class="catalog-tiles__img"  src="<?php echo $block->getViewFileUrl("images/catalog-tiles/web/9 61.png")?>" alt="9 61">
        <div class="catalog-tiles__img-bottom-container">
            <h3 class="catalog-tiles__img-bottom-title">Sardinia White</h3>
            <div class="catalog-tiles__img-bottom-content">
                <span class="catalog-tiles__canceled-sar">449.99 SAR</span>
                <span class="catalog-tiles__sar">312.49 SAR</span>
            </div>
        </div>
    </div>
    <div class="catalog-tiles__img-container">
        <img width="333" height="333" class="catalog-tiles__img"  src="<?php echo $block->getViewFileUrl("images/catalog-tiles/web/8 1.png")?>" alt="8 1">
        <div class="catalog-tiles__img-bottom-container">
            <h3 class="catalog-tiles__img-bottom-title">Sicily Grey 30×60</h3>
            <div class="catalog-tiles__img-bottom-content">
                <span class="catalog-tiles__canceled-sar">449.99 SAR</span>
                <span class="catalog-tiles__sar">312.49 SAR</span>
            </div>
        </div>
    </div>
</div>

<button type="button" class="catalog-tiles__btn catalog-tiles__btn--primary">
        Load More
</button>
    