<section class="catalog-category-list__section">
    <div class="catalog-category-list__content-container">
        <p class="catalog-category-list__subtitle">Lorem Ipsum</p>
        <h3 class="catalog-category-list__title">Categories</h3>
        <p class="catalog-category-list__content">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,</p>
    </div>
</section>

<section class="catalog-category-list__section">
    <img width="332" height="401" class="catalog-category-list__img catalog-category-list__img"  src="<?php echo $block->getViewFileUrl("images/catalog-categories/catalog-category-1.png")?>" alt="catalog-category-1">
    <div class="catalog-category-list__content-container">
        <p class="catalog-category-list__subtitle">Lorem Ipsum</p>
        <h3 class="catalog-category-list__title">Lorem Ipsum</h3>
        <p class="catalog-category-list__content">Lorem Ipsum</p>
    </div>
</section>

<section class="catalog-category-list__section">
    <img width="332" height="401" class="catalog-category-list__img catalog-category-list__img"  src="<?php echo $block->getViewFileUrl("images/catalog-categories/catalog-category-2.png")?>" alt="catalog-category-2">
    <div class="catalog-category-list__content-container">
        <p class="catalog-category-list__subtitle">Lorem Ipsum</p>
        <h3 class="catalog-category-list__title">Lorem Ipsum</h3>
        <p class="catalog-category-list__content">Lorem Ipsum</p>
    </div>
</section>


<section class="catalog-category-list__section">
    <img width="332" height="401" class="catalog-category-list__img catalog-category-list__img"  src="<?php echo $block->getViewFileUrl("images/catalog-categories/catalog-category-3.png")?>" alt="catalog-category-3">
    <div class="catalog-category-list__content-container">
        <p class="catalog-category-list__subtitle">Lorem Ipsum</p>
        <h3 class="catalog-category-list__title">Lorem Ipsum</h3>
        <p class="catalog-category-list__content">Lorem Ipsum</p>
    </div>
</section>


