<h2 class="pdp-viewed-products__title">Recently Viewed Products</h2>
<div class="pdp-viewed-products__tiles-container">
    <div class="pdp-viewed-products__img-container">
        <img width="333" height="333" class="pdp-viewed-products__img"  src="<?php echo $block->getViewFileUrl("images/pdp/web/11 1.png")?>" alt="11 1">
        <div class="pdp-viewed-products__img-bottom-container">
            <h3 class="pdp-viewed-products__img-bottom-title">Windsor White Oak</h3>
            <div class="pdp-viewed-products__img-bottom-content">
                <span class="pdp-viewed-products__canceled-sar">449.99 SAR</span>
                <span class="pdp-viewed-products__sar">312.49 SAR</span>
            </div>
        </div>
    </div>
    <div class="pdp-viewed-products__img-container">
        <img width="333" height="333" class="pdp-viewed-products__img"  src="<?php echo $block->getViewFileUrl("images/pdp/web/10 1.png")?>" alt="10 1">
        <div class="pdp-viewed-products__img-bottom-container">
            <h3 class="pdp-viewed-products__img-bottom-title">Sicily Grey Décor 30×60</h3>
            <div class="pdp-viewed-products__img-bottom-content">
                <span class="pdp-viewed-products__canceled-sar">449.99 SAR</span>
                <span class="pdp-viewed-products__sar">312.49 SAR</span>
            </div>
        </div>
    </div>
    <div class="pdp-viewed-products__img-container">
        <img width="333" height="333" class="pdp-viewed-products__img"  src="<?php echo $block->getViewFileUrl("images/pdp/web/9 61.png")?>" alt="9 61">
        <div class="pdp-viewed-products__img-bottom-container">
            <h3 class="pdp-viewed-products__img-bottom-title">Sardinia White</h3>
            <div class="pdp-viewed-products__img-bottom-content">
                <span class="pdp-viewed-products__canceled-sar">449.99 SAR</span>
                <span class="pdp-viewed-products__sar">312.49 SAR</span>
            </div>
        </div>
    </div>
    <div class="pdp-viewed-products__img-container">
        <img width="333" height="333" class="pdp-viewed-products__img"  src="<?php echo $block->getViewFileUrl("images/pdp/web/8 1.png")?>" alt="8 1">
        <div class="pdp-viewed-products__img-bottom-container">
            <h3 class="pdp-viewed-products__img-bottom-title">Sicily Grey 30×60</h3>
            <div class="pdp-viewed-products__img-bottom-content">
                <span class="pdp-viewed-products__canceled-sar">449.99 SAR</span>
                <span class="pdp-viewed-products__sar">312.49 SAR</span>
            </div>
        </div>
    </div>
</div>