<div class="catalog-hero__img-container">
    <img width="1920" height="526" class="catalog-hero__img catalog-hero__img"  src="<?php echo $block->getViewFileUrl("images/catalog-hero.png")?>" alt="catalog-hero">
</div>
<section class="catalog-hero__section">   
    <h2 class="catalog-hero__title">Catalog</h2>
    <p class="catalog-hero__content">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text.
    </p>
</section>